import { Project, Skill, SocialLink, Certification } from './types';

export const projects: Project[] = [
  {
    id: '1',
    slug: 'my-wardrobe-app',
    title: 'MyWardrobeApp',
    description: "A centralized digital wardrobe for the whole family, designed to organize, track, and manage clothing inventory with ease.",
    longDescription: 'A centralized digital wardrobe for the whole family designed to simplify clothing management. Built with Vite and React for a high-performance frontend, the app uses Sequelize to manage complex relational data for multiple users. By organizing and tracking inventory in one intuitive dashboard, it transforms the mundane task of wardrobe organization into a streamlined, automated experience for every household member.',
    tags: ['Vite', 'React', 'PostgreSQL', 'Sequelize', 'Weather API', 'Gemini API',],
    images: ['https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421657/IP_Outfit_Recommendation_Page_u7kusk.png',"https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421658/Screenshot_2025-12-18_171958_envuzv.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421658/Screenshot_2025-12-18_170418_fb3c3s.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421657/IP_Add_Item_Page_vuwehl.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421656/IP_Home_Page_lyml7a.png"],
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com/yourusername/project-alpha',
    featured: true,
  },
 {
    id: '2',
    slug: 'crucial-website-clone',
    title: 'Crucial Website Clone',
    description: 'A high-performance reconstruction of the Crucial hardware site, built to master type-safe architecture and server-side rendering.',
    longDescription: 'A technical deep-dive into the Next.js ecosystem, this project involved recreating the complex UI of the Crucial website. The primary goal was to implement a robust, type-safe codebase using TypeScript while leveraging Next.js for optimized performance. It features a responsive layout, and modular component architecture.',
    tags: ['TypeScript', 'Next.js', 'Tailwind CSS', 'React', 'DaisyUI'],
    images: ['https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421656/Crucial_RAM_page_r6s7fz.png', "https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421656/Crucial_hover_RAM_nugc41.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421656/Crucial_home_page_sjtcie.png"], 
    liveUrl: 'https://example.com',
    featured: false,
  },
 {
    id: '3',
    slug: 'twitter-clone-mobile',
    title: 'Twitter Clone',
    description: 'A cross-platform mobile social media application focused on real-time data fetching and complex relational schemas.',
    longDescription: 'This project serves as a deep dive into the Apollo/GraphQL ecosystem. By building a Twitter-inspired interface with Expo Go, I implemented intricate features such as nested reply threads and user interactions. The focus was on optimizing query performance with Apollo Client and managing a relational database via a GraphQL gateway to ensure a smooth, reactive mobile user experience.',
    tags: ['React Native', 'GraphQL', 'Apollo', 'Expo Go'],
    images: ['/projects/twitter-clone.jpg'],
    liveUrl: 'https://github.com/your-username/your-repo',
    featured: true,
  },
  {
    id: '4',
    slug: 'my-cuisine-app-backend',
    title: 'MyCuisineApp - Backend API',
    description: 'A robust RESTful API for restaurant management featuring secure authentication, role-based access control, and cloud-integrated image processing.',
    longDescription: 'Developed as a comprehensive backend solution, this project manages a complex cuisine and category ecosystem. It features a dual-layer access system: a public-facing API with advanced filtering/pagination and a protected administrative dashboard. Key technical highlights include custom middleware for JWT authentication, role-based authorization (RBAC), centralized error handling for Sequelize, and seamless image hosting integration via the Cloudinary API.',
    tags: ['Node JS', 'Express', 'Sequelize', 'PostgreSQL', 'JWT', 'Cloudinary'],
    images: ['/projects/api-documentation.jpg'],
    liveUrl: 'https://github.com/your-username/your-repo',
    featured: false,
  },
  {
    id: '5',
    slug: 'type-royale',
    title: 'Type Royale',
    description: 'A competitive typing game that challenges players to out-type their opponents in real-time multiplayer matches.',
    longDescription: 'Type Royale is an engaging multiplayer typing game where players compete to type words accurately and quickly. Built with a focus on real-time interaction, the game features a sleek UI and responsive design. Players can join matches, track their scores, and improve their typing skills in a fun, competitive environment.',
    tags: ['JavaScript', 'HTML', 'CSS', 'Socket.io', 'Node.js'],
    images: ['https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421657/GP_Login_and_Register_pomwwq.png',"https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421657/GP_Join_Room_ngxqaq.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421656/GP_Create_Room_mk2fbb.png","https://res.cloudinary.com/db3xxjbxj/image/upload/v1769421657/GP_Home_Page_ixfzk3.png"],
    liveUrl: 'https://example.com',
    githubUrl: 'https://github.com/your-username/your-repo',
    featured: false,
  },
  {
    id: '6',
    slug: 'my-cuisine-app-frontend',
    title: 'MyCuisineApp - Frontend',
    description: 'A user-friendly restaurant management dashboard with dynamic filtering, responsive design, and seamless API integration.',
    longDescription: "This frontend application serves as the user interface for the MyCuisineApp backend API. It features a clean, intuitive design that allows restaurant managers to easily navigate and manage their cuisine and category data. Key functionalities include dynamic filtering, pagination, and real-time updates through seamless integration with the backend API.",
    tags: ['React', 'Tailwind CSS', 'Axios', 'REST API'],
    images: ['/projects/restaurant-dashboard.jpg'],
    liveUrl: 'https://example.com',
    githubUrl: ' ',
    featured: false,
  }
];

export const skills: Skill[] = [
  
  { name: 'React', category: 'frontend', level: 90 },
  { name: 'Next.js', category: 'frontend', level: 85 },
  { name: 'React Native', category: 'frontend', level: 80 },
  { name: 'TypeScript', category: 'frontend', level: 85 },
  { name: 'Tailwind CSS', category: 'frontend', level: 90 },
  { name: 'Vite', category: 'frontend', level: 85 },

  { name: 'Node.js', category: 'backend', level: 85 },
  { name: 'Express', category: 'backend', level: 85 },
  { name: 'GraphQL', category: 'backend', level: 75 },
  { name: 'Apollo Client', category: 'backend', level: 75 },
  { name: 'Sequelize', category: 'backend', level: 85 },
  { name: 'PostgreSQL', category: 'backend', level: 80 },
  { name: 'JWT Authentication', category: 'backend', level: 80 },

  { name: 'Git', category: 'tools', level: 85 },
  { name: 'Expo Go', category: 'tools', level: 80 },
  { name: 'Cloudinary', category: 'tools', level: 75 },
  { name: 'Gemini/OpenAI API', category: 'tools', level: 70 },

  { name: 'JavaScript', category: 'languages', level: 95 },
 
];

export const socialLinks: SocialLink[] = [
  { name: 'GitHub', url: 'https://github.com/AuliaFHanif', icon: 'github' },
  { name: 'LinkedIn', url: 'https://www.linkedin.com/in/aulia-farhan-hanif-53b69b377/', icon: 'linkedin' },
  { name: 'Email', url: 'fhanif180902@email.com', icon: 'mail' },
];

export const certifications: Certification[] = [
  {
    id: '1',
    slug: 'toefl-itp',
    name: 'TOEFL ITP (Score: 630/677)',
    issuer: 'Educational Testing Service (ETS)',
    date: 'Jan 2024',
    credentialUrl: 'https://drive.google.com/file/d/1L5DMrn99n6Knpt3IggYH7S2xUNXeblHR/view?usp=drive_link',
    imageUrl: '/images/toefl-itp.png',
  },
  {
    id: '2',
    slug: 'hackerrank-react-basic',
    name: 'React (Basic)',
    issuer: 'HackerRank',
    date: 'Jan 2026',
    credentialUrl: 'https://www.hackerrank.com/certificates/iframe/394738b5d0a8',
    imageUrl: '/images/hackerrank-react-basic.png',
  },
  {
    id: '3',
    slug: 'jlpt-n2',
    name: 'Japanese Language Proficiency Test N2',
    issuer: 'Japan Foundation',
    date: 'Aug 2023',
    credentialUrl: 'https://drive.google.com/file/d/1YZ3wza2QxveBx6zymYLze2dRbWkUeSYo/view?usp=sharing',
  },
  {
    id: '4',
    slug: 'hackerrank-sw-intern',
    name: 'Software Engineering Intern',
    issuer: 'HackerRank',
    date: 'Jan 2026',
    credentialUrl: 'https://www.hackerrank.com/certificates/iframe/2a5f2e9f0e42',
  },
  {
    id: '5',
    slug: 'hackerrank-css-basic',
    name: 'CSS (Basic)',
    issuer: 'HackerRank',
    date: 'Jan 2026',
    credentialUrl: 'https://www.hackerrank.com/certificates/iframe/7cc99182ebe1',
  },
  {
    id: '6',
    slug: 'hackerrank-problem-solving-basic',
    name: 'Problem Solving (Basic)',
    issuer: 'HackerRank',
    date: 'Jan 2026',
    credentialUrl: 'https://www.hackerrank.com/certificates/iframe/a6cea99d5971',
  },
  {
    id: '7',
    slug: 'hackerrank-javascript-basic',
    name: 'JavaScript (Basic)',
    issuer: 'HackerRank',
    date: 'Jan 2026',
    credentialUrl: 'https://www.hackerrank.com/certificates/iframe/b34c8ec4888b',
  },
];